export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_LOGIN_ERROR_MESSAGE = 'CLEAR_LOGIN_ERROR_MESSAGE';
export const CLEAR_LOGIN_SUCCESS_MESSAGE = 'CLEAR_LOGIN_SUCCESS_MESSAGE';
